# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions 
#
name: Generate Cypress Reports for Botflows 
on:
  push:
    branches:
     - 'main'
     
  schedule:
    # * is a special character in YAML so you have to quote this string
    #- cron:  '*/180 * * * *'

     
jobs:
  cypress-test:
    name: Run on Chrome 83
    runs-on: ubuntu-18.04
    container: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - uses: actions/checkout@v2
      
      - name: Install cypress and verify
        run: 
          npm ci
          $(npm bin)/cypress verify
          
      - name: Run Cypress tests
        run: npm run test:chrome
        continue-on-error: false
        
      - name: Copy test execution videos and screenshots
        run: |
          mkdir public
          cp -r cypress/videos public/videos
          cp -r cypress/screenshots public/screenshots
          
      - name: Merge test reports
        run: npm run combine:report

      - name: Generate HTML report
        run: npm run generate:report
        
      - name: Deploy report page to Github page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          
      - name: Send mail
        if: always()
        uses: dawidd6/action-send-mail@v2
        with:
          # mail server settings
          server_address: smtp.gmail.com
          server_port: 465
          # user credentials
          username: ${{ secrets.USER_NAME }}
          password: ${{ secrets.PASSWORD }}
          # email subject
          subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
          # email body as text
          body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
          # comma-separated string, send email to
          to: johndoe@gmail.com,doejohn@gmail.com,jaffarsadhik@outlook.com
          # from email name
          from: John Doe
          
        
